app:
  github-token: ${GITHUB_TOKEN}
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}

domains:
  github: "https://api.github.com"
  stackoverflow: "https://api.stackexchange.com/2.3"
  bot: "http://localhost:8090"
  telegram-bot-url: "http://localhost:8080"

db:
  access-type: SQL # или SQL

spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper_db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
