app:
  github-token: ${GITHUB_TOKEN}
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}


messaging:
  message-transport: Kafka # HTTP \ Kafka

domains:
  github: "https://api.github.com"
  stackoverflow: "https://api.stackexchange.com/2.3"
  bot: "http://localhost:8090"
  telegram-bot-url: "http://localhost:8080"

#logging:
#  structured:
#    format:
#      console: ecs


scheduler:
  delay: 5s
  fixed-delay: 5s

db:
  access-type: JPA # JPA или SQL

#logging:
#  structured:
#    format:
#      console : none

spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper_db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
    topics:
      link-update:
        name: link-updates-topic
        partitions: 3
        replicas: 1

    admin:
      properties:
        bootstrap.servers: localhost:9092

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
