global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['your-app:9091']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
